name: Testplugin
version: ${project.version}
main: de.polygondev.testplugin.Testplugin
api-version: 1.18
depend: [
    InventoryApi
]
commands:
  invopen:
    description: ja so und nu?
    usage: invopen